language: node
install:
- npm install
after_success:
- cp -R ./dist/* .
- rm -rf dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
